{
 "title": "Home",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Yavar - Enp1S0 - Status",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\n\nFinalOutput = [\"_field\", \"_time\", \"_value\"]\n\nRawSeries = from(bucket: \"CPEDevice\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"yavar\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"syslog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"message\")\n  |> filter(fn: (r) => r[\"appname\"] == \"main.py\")\n  |> map(fn: (r) => {\n      parts = strings.split(v: r._value, t: \" | \")\n      splittedMessage = strings.split(v: parts[1], t: \" interface is \")\n      return {_start: r._start, _stop: r._stop, _time: r._time, _value: splittedMessage[1], _field: splittedMessage[0]}\n    })\n  |> filter(fn: (r) => r[\"_field\"] == \"enp1s0\")  \n  |> map(fn: (r) => ({\n    r with\n    _value:\n      if r._value == \"ACTIVE\" then 2\n      else if r._value == \"INACTIVE\" then 1\n      else 0\n  })) \n  |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Yavar - Enp2S0 - Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\n\nFinalOutput = [\"_field\", \"_time\", \"_value\"]\n\nRawSeries = from(bucket: \"CPEDevice\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"yavar\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"syslog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"message\")\n  |> filter(fn: (r) => r[\"appname\"] == \"main.py\")\n  |> map(fn: (r) => {\n      parts = strings.split(v: r._value, t: \" | \")\n      splittedMessage = strings.split(v: parts[1], t: \" interface is \")\n      return {_start: r._start, _stop: r._stop, _time: r._time, _value: splittedMessage[1], _field: splittedMessage[0]}\n    })\n  |> filter(fn: (r) => r[\"_field\"] == \"enp2s0\")  \n  |> map(fn: (r) => ({\n    r with\n    _value:\n      if r._value == \"ACTIVE\" then 2\n      else if r._value == \"INACTIVE\" then 1\n      else 0\n  })) \n  |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Netcon - Enp1S0 - Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\n\nFinalOutput = [\"_field\", \"_time\", \"_value\"]\n\nRawSeries = from(bucket: \"CPEDevice\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"netcon\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"syslog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"message\")\n  |> filter(fn: (r) => r[\"appname\"] == \"main.py\")\n  |> map(fn: (r) => {\n      parts = strings.split(v: r._value, t: \" | \")\n      splittedMessage = strings.split(v: parts[1], t: \" interface is \")\n      return {_start: r._start, _stop: r._stop, _time: r._time, _value: splittedMessage[1], _field: splittedMessage[0]}\n    })\n  |> filter(fn: (r) => r[\"_field\"] == \"enp1s0\")  \n  |> map(fn: (r) => ({\n    r with\n    _value:\n      if r._value == \"ACTIVE\" then 2\n      else if r._value == \"INACTIVE\" then 1\n      else 0\n  })) \n  |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Netcon - Enp2S0 - Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\n\nFinalOutput = [\"_field\", \"_time\", \"_value\"]\n\nRawSeries = from(bucket: \"CPEDevice\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"host\"] == \"netcon\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"syslog\")\n  |> filter(fn: (r) => r[\"_field\"] == \"message\")\n  |> filter(fn: (r) => r[\"appname\"] == \"main.py\")\n  |> map(fn: (r) => {\n      parts = strings.split(v: r._value, t: \" | \")\n      splittedMessage = strings.split(v: parts[1], t: \" interface is \")\n      return {_start: r._start, _stop: r._stop, _time: r._time, _value: splittedMessage[1], _field: splittedMessage[0]}\n    })\n  |> filter(fn: (r) => r[\"_field\"] == \"enp2s0\")  \n  |> map(fn: (r) => ({\n    r with\n    _value:\n      if r._value == \"ACTIVE\" then 2\n      else if r._value == \"INACTIVE\" then 1\n      else 0\n  })) \n  |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Configuration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "errorConfiguration = from(bucket: \"CPEDevice\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"syslog\")\n  |> filter(fn: (r) => r[\"appname\"] == \"chiefnet\")\n  |> filter(fn: (r) => r[\"_field\"] == \"message\")\n  |> filter(fn: (r) => r[\"severity\"] == \"err\")\n  |> count()\n\ninfoConfiguration = from(bucket: \"CPEDevice\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"syslog\")\n  |> filter(fn: (r) => r[\"appname\"] == \"chiefnet\")\n  |> filter(fn: (r) => r[\"_field\"] == \"message\")\n  |> filter(fn: (r) => r[\"severity\"] == \"info\")\n  |> count()\n\nunion(tables: [errorConfiguration, infoConfiguration])\n  |> group()\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Info",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"CPEDevice\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"syslog\")\n  |> filter(fn: (r) => r[\"appname\"] == \"chiefnet\")\n  |> filter(fn: (r) => r[\"_field\"] == \"message\")\n  |> filter(fn: (r) => r[\"severity\"] == \"info\")\n  |> drop(columns: [\"host\", \"appname\", \"facility\", \"hostname\", \"severity\"])\n  |> count()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"CPEDevice\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"syslog\")\n  |> filter(fn: (r) => r[\"appname\"] == \"chiefnet\")\n  |> filter(fn: (r) => r[\"_field\"] == \"message\")\n  |> filter(fn: (r) => r[\"severity\"] == \"err\")\n  |> drop(columns: [\"host\", \"appname\", \"facility\", \"hostname\", \"severity\"])\n  |> count()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 5 Failed Configurations",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\n\nFinalOutput = [\"_field\", \"_time\", \"_value\"]\n\nRawSeries = from(bucket: \"CPEDevice\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"syslog\")\n  |> filter(fn: (r) => r[\"appname\"] == \"chiefnet\")\n  |> filter(fn: (r) => r[\"_field\"] == \"message\")\n  |> filter(fn: (r) => r[\"severity\"] == \"err\")\n  |> map(fn: (r) => {\n      parts = strings.split(v: r._value, t: \" | \")\n      return { Name: strings.toUpper(v: parts[4]), Errors: parts[2],}\n    })\n  |> group(columns: [\"Name\"])\n  |> count(column: \"Errors\")\n  |> group()\n  |> sort(columns: [\"Errors\"], desc: true)\n  |> limit(n:5, offset: 0)\n  |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Top 3 Failed CPE Devices",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"strings\"\n\nFinalOutput = [\"_field\", \"_time\", \"_value\"]\n\nRawSeries = from(bucket: \"CPEDevice\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"syslog\")\n  |> filter(fn: (r) => r[\"appname\"] == \"chiefnet\")\n  |> filter(fn: (r) => r[\"_field\"] == \"message\")\n  |> filter(fn: (r) => r[\"severity\"] == \"err\")\n  |> map(fn: (r) => {\n      parts = strings.split(v: r._value, t: \" | \")\n      return { DeviceName: strings.toUpper(v: r.hostname), Errors: parts[2],}\n    })\n  |> group(columns: [\"DeviceName\"])\n  |> count(column: \"Errors\")\n  |> group()\n  |> sort(columns: [\"Errors\"], desc: true)\n  |> limit(n:5, offset: 0)\n  |> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Network Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"CPEDevice\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"exec_mycollector\")\n  |> filter(fn: (r) => r[\"_field\"] == \"ifname\" or r[\"_field\"] == \"operstate\")\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n  |> last(column: \"ifname\")\n  |> group()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}